const xml2js = require('xml2js');

// XML string to be parsed to JSON
const xml = `<?xml version="1.0" encoding="UTF-8"?>
<Chart>
<Symbol>
<DESCRIPTION>S&amp;P 500 CONSUMER DISCRETIONARY SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPD</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.92</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-2.79</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-1.87</MONTH_CHANGE>
<THREE_MONTH_CHANGE>0.89</THREE_MONTH_CHANGE>
<YTD_CHANGE>-5.87</YTD_CHANGE>
<ONE_YEAR_CHANGE>14.25</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>81.29</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>126.34</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 CONSUMER STAPLES SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPS</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.49</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-1.19</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>1.55</MONTH_CHANGE>
<THREE_MONTH_CHANGE>7.80</THREE_MONTH_CHANGE>
<YTD_CHANGE>-1.53</YTD_CHANGE>
<ONE_YEAR_CHANGE>17.24</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>48.94</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>47.72</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 ENERGY SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPE</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>0.40</DAY_CHANGE> 
<FIVE_DAY_CHANGE>5.93</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>20.87</MONTH_CHANGE>
<THREE_MONTH_CHANGE>13.70</THREE_MONTH_CHANGE>
<YTD_CHANGE>16.85</YTD_CHANGE>
<ONE_YEAR_CHANGE>53.13</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>6.79</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>-10.25</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>-6.14</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 FINANCIALS SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPF</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-2.30</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-2.83</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>3.78</MONTH_CHANGE>
<THREE_MONTH_CHANGE>1.01</THREE_MONTH_CHANGE>
<YTD_CHANGE>2.08</YTD_CHANGE>
<ONE_YEAR_CHANGE>29.25</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>56.35</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>73.83</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 HEALTH CARE SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP>78378P104</CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPA</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.39</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-2.68</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-3.89</MONTH_CHANGE>
<THREE_MONTH_CHANGE>3.34</THREE_MONTH_CHANGE>
<YTD_CHANGE>-6.24</YTD_CHANGE>
<ONE_YEAR_CHANGE>13.07</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>49.56</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>88.94</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>273.44</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 INDUSTRIALS SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPI</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.19</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-0.66</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>2.38</MONTH_CHANGE>
<THREE_MONTH_CHANGE>1.68</THREE_MONTH_CHANGE>
<YTD_CHANGE>-1.16</YTD_CHANGE>
<ONE_YEAR_CHANGE>17.77</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>52.67</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>63.20</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 INFORMATION TECHNOLOGY SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPT</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-2.49</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-2.65</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-3.64</MONTH_CHANGE>
<THREE_MONTH_CHANGE>3.65</THREE_MONTH_CHANGE>
<YTD_CHANGE>-7.12</YTD_CHANGE>
<ONE_YEAR_CHANGE>26.64</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>151.20</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>241.48</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 MATERIALS SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPM</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.32</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-0.92</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>0.36</MONTH_CHANGE>
<THREE_MONTH_CHANGE>4.23</THREE_MONTH_CHANGE>
<YTD_CHANGE>-3.36</YTD_CHANGE>
<ONE_YEAR_CHANGE>16.13</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>67.02</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>72.92</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 REAL ESTATE SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPRE</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-0.71</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-2.10</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-3.60</MONTH_CHANGE>
<THREE_MONTH_CHANGE>4.08</THREE_MONTH_CHANGE>
<YTD_CHANGE>-7.49</YTD_CHANGE>
<ONE_YEAR_CHANGE>32.82</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>48.76</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>56.86</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 TELECOMMUNICATION SERVICES SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPL</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.99</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-1.50</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-2.46</MONTH_CHANGE>
<THREE_MONTH_CHANGE>-5.47</THREE_MONTH_CHANGE>
<YTD_CHANGE>-4.12</YTD_CHANGE>
<ONE_YEAR_CHANGE>20.15</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>72.14</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>47.95</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 UTILITIES SECTOR</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP></CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.GSPU</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.20</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-1.96</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-1.39</MONTH_CHANGE>
<THREE_MONTH_CHANGE>4.43</THREE_MONTH_CHANGE>
<YTD_CHANGE>-4.16</YTD_CHANGE>
<ONE_YEAR_CHANGE>8.82</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>29.38</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>39.90</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>--</TEN_YEAR_CHANGE>
</Symbol>
<Symbol>
<DESCRIPTION>S&amp;P 500 INDEX</DESCRIPTION>
<SC_CODE>I</SC_CODE>
<CUSIP>648815108</CUSIP>
<TIMEZONEOFFSET>-18000</TIMEZONEOFFSET>
<IDENTIFIER>.SPX</IDENTIFIER>
<LAST_DATE>20220118-16:00:00</LAST_DATE>
<DAY_CHANGE>-1.84</DAY_CHANGE> 
<FIVE_DAY_CHANGE>-2.00</FIVE_DAY_CHANGE> 
<MONTH_CHANGE>-0.94</MONTH_CHANGE>
<THREE_MONTH_CHANGE>2.36</THREE_MONTH_CHANGE>
<YTD_CHANGE>-3.97</YTD_CHANGE>
<ONE_YEAR_CHANGE>21.47</ONE_YEAR_CHANGE>
<THREE_YEAR_CHANGE>73.64</THREE_YEAR_CHANGE>
<FIVE_YEAR_CHANGE>101.82</FIVE_YEAR_CHANGE>
<TEN_YEAR_CHANGE>253.81</TEN_YEAR_CHANGE>
</Symbol>
</Chart>`;



// convert XML to JSON
xml2js.parseString(xml, (err, result) => {
    if(err) {
        throw err;
    }

    // `result` is a JavaScript object
    // convert it to a JSON string
    const json = JSON.stringify(result, null, 4);
    console.log(json);

    // // log JSON string
    // const value = JSON.parse(json);
    // //console.log(json);
    // //console.log(value["Chart"]["Symbol"]);
    // for(var i = 0; i < Object.keys(value["Chart"]["Symbol"]).length; i++){
    //     console.log(value["Chart"]["Symbol"][i]["IDENTIFIER"]);
    // }
});